"use client";

import "./SearchDialog.css";

import * as React from "react";
import { useRouter } from "next/navigation";
import { Autocomplete } from "@base-ui/react/autocomplete";
import type MiniSearch from "minisearch";
import CloseIcon from "@brijbyte/md3-icons/outlined/Close";
import SearchIcon from "@brijbyte/md3-icons/outlined/Search";
import { Dialog, DialogContent } from "@/ui/dialog";
import { IconButton } from "@/ui/icon-button";
import { List, ListItem } from "@/ui/list";
import { TextField } from "@/ui/text-field";
import { Typography } from "@/ui/typography";
import { NAV, SECTIONS, SHOWCASES, type NavItem } from "@/nav";

// Docs search: minisearch over public/search-index.json (headings + prose,
// generated by scripts/build-search-index.mjs) joined with NAV for page
// titles/descriptions — so showcase/landing pages are findable by title too.
// One dialog instance lives in the (docs) layout; triggers open it via a
// window event so sidebar and header don't each need their own state.

type IndexPage = { route: string; sections: { id: string; heading: string; text: string }[] };

// One doc per page (title + description) plus one per h2/h3 section (heading +
// text). Section docs don't index the page title, so a title query surfaces
// the page once instead of every one of its sections.
type SearchDoc = {
  id: string;
  route: string;
  anchor?: string;
  page: string;
  title?: string;
  description?: string;
  heading?: string;
  text?: string;
};

type SearchHit = Omit<SearchDoc, "title"> & { id: string };

const OPEN_EVENT = "md3docs:open-search";
const NAV_BY_ROUTE = new Map(NAV.map((item) => [item.path, item]));

export function openSearch() {
  window.dispatchEvent(new Event(OPEN_EVENT));
}

// Engine loads once per session: minisearch and the index JSON are both
// fetched lazily on first open, never in the page bundle.
let enginePromise: Promise<MiniSearch<SearchDoc>> | null = null;
function loadEngine() {
  enginePromise ??= (async () => {
    const [{ default: MiniSearchCtor }, pages] = await Promise.all([
      import("minisearch"),
      // Inlined from next.config.ts: plain name in dev, content-hashed in prod.
      fetch(process.env.NEXT_PUBLIC_SEARCH_INDEX_URL ?? "/search-index.json").then(
        (res) => res.json() as Promise<IndexPage[]>,
      ),
    ]);
    const docs: SearchDoc[] = NAV.map((item) => ({
      id: item.path,
      route: item.path,
      page: item.title,
      title: item.title,
      description: item.description,
    }));
    for (const { route, sections } of pages) {
      const page = NAV_BY_ROUTE.get(route)?.title ?? route;
      for (const section of sections) {
        docs.push({
          id: `${route}#${section.id}`,
          route,
          anchor: section.id || undefined,
          page,
          heading: section.heading || undefined,
          text: section.text || undefined,
        });
      }
    }
    const mini = new MiniSearchCtor<SearchDoc>({
      fields: ["title", "description", "heading", "text"],
      storeFields: ["route", "anchor", "page", "description", "heading", "text"],
      searchOptions: {
        boost: { title: 5, heading: 3, description: 2 },
        prefix: true,
        fuzzy: 0.15,
      },
    });
    mini.addAll(docs);
    return mini;
  })();
  return enginePromise;
}

const hitHref = (hit: SearchHit) => (hit.anchor ? `${hit.route}#${hit.anchor}` : hit.route);

// A rendered result row; hits and browse-mode nav items share this shape.
type Row = {
  key: string;
  href: string;
  route: string;
  title: string;
  supporting?: string;
  icon?: NavItem["icon"];
};

type RowGroup = { label?: string; rows: Row[] };

const navRow = (item: NavItem): Row => ({
  key: item.path,
  href: item.path,
  route: item.path,
  title: item.label,
  supporting: item.description,
  icon: item.icon,
});

// Browse mode (empty query): the sidebar nav's sections plus the showcases,
// which have no sidebar entry.
const BROWSE_GROUPS: RowGroup[] = [
  ...SECTIONS.map((section) => ({ label: section.label, rows: section.items.map(navRow) })),
  { label: "Showcase", rows: SHOWCASES.map(navRow) },
];

const hitRow = (hit: SearchHit): Row => ({
  key: hit.id,
  href: hitHref(hit),
  route: hit.route,
  title: hit.heading ?? hit.page,
  supporting: hit.heading ? [hit.page, hit.text].filter(Boolean).join(" — ") : hit.description,
  icon: NAV_BY_ROUTE.get(hit.route)?.icon,
});

export function SearchDialog() {
  const router = useRouter();
  const [open, setOpen] = React.useState(false);
  const [query, setQuery] = React.useState("");
  const [engine, setEngine] = React.useState<MiniSearch<SearchDoc> | null>(null);

  React.useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") {
        event.preventDefault();
        setOpen(true);
      }
    };
    const onOpen = () => setOpen(true);
    window.addEventListener("keydown", onKeyDown);
    window.addEventListener(OPEN_EVENT, onOpen);
    return () => {
      window.removeEventListener("keydown", onKeyDown);
      window.removeEventListener(OPEN_EVENT, onOpen);
    };
  }, []);

  React.useEffect(() => {
    if (open) loadEngine().then(setEngine);
  }, [open]);

  const groups = React.useMemo<RowGroup[]>(() => {
    if (!query.trim()) return BROWSE_GROUPS;
    if (!engine) return [];
    const hits = engine.search(query).slice(0, 10) as unknown as SearchHit[];
    return [{ rows: hits.map(hitRow) }];
  }, [engine, query]);
  const rows = groups.flatMap((group) => group.rows);

  const go = (row: Row) => {
    setOpen(false);
    router.push(row.href);
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogContent className="docs-search-dialog" aria-label="Search documentation">
        {/* ARIA combobox semantics via Base UI Autocomplete (its Combobox is
            for value selection, not free-form search widgets). No Portal/
            Positioner: the List renders inline in the dialog, which Base UI
            supports (the list element doubles as the positioner). `open` is
            pinned; a close request (Escape) closes the whole dialog instead. */}
        <Autocomplete.Root
          filter={null}
          open
          onOpenChange={(next) => {
            if (!next) setOpen(false);
          }}
          value={query}
          onValueChange={setQuery}
          itemToStringValue={(row: Row) => row.title}
          autoHighlight
        >
          {/* MD3 docked-search-view header, built from the library TextField:
              docs CSS squares its container and drops the fill (stable public
              class names), so the filled variant's active indicator doubles as
              the header/results divider — no box fighting the popup's corners.
              The render prop lands the combobox input props on TextField's
              inner <input> (rest props spread onto the control). */}
          <Autocomplete.Input
            render={
              <TextField
                variant="filled"
                className="docs-search-field"
                leadingIcon={<SearchIcon />}
                trailingIcon={
                  query ? (
                    <Autocomplete.Clear
                      render={<IconButton aria-label="Clear search" />}
                      onClick={() => setQuery("")}
                    >
                      <CloseIcon />
                    </Autocomplete.Clear>
                  ) : undefined
                }
                placeholder="Search the docs"
                aria-label="Search the docs"
                autoFocus
              />
            }
          />
          {rows.length > 0 ? (
            <Autocomplete.List
              render={<List className="docs-search-results" />}
              aria-label="Search results"
            >
              {groups.map((group) => (
                <Autocomplete.Group
                  key={group.label ?? "results"}
                  className="contents"
                  items={group.rows}
                >
                  {group.label && (
                    <Autocomplete.GroupLabel
                      render={
                        <Typography
                          as="div"
                          variant="title-small"
                          className="px-4 pt-4 pb-1 font-brand text-on-surface-variant"
                        />
                      }
                    >
                      {group.label}
                    </Autocomplete.GroupLabel>
                  )}
                  {group.rows.map((row) => (
                    <Autocomplete.Item
                      key={row.key}
                      value={row}
                      onClick={() => go(row)}
                      render={
                        <ListItem
                          as="li"
                          leading={row.icon ? <row.icon /> : <SearchIcon />}
                          supportingText={
                            row.supporting ? (
                              <span className="docs-search-snippet">{row.supporting}</span>
                            ) : undefined
                          }
                        />
                      }
                    >
                      {row.title}
                    </Autocomplete.Item>
                  ))}
                </Autocomplete.Group>
              ))}
            </Autocomplete.List>
          ) : (
            <Typography variant="body-medium" className="docs-search-empty text-on-surface-variant">
              {engine ? `No results for “${query.trim()}”` : "Loading search index…"}
            </Typography>
          )}
        </Autocomplete.Root>
      </DialogContent>
    </Dialog>
  );
}

// Sidebar trigger, styled as a compact MD3 search bar. The shortcut hint
// renders post-mount only (platform-dependent, would mismatch hydration).
export function SearchButton() {
  const [keys, setKeys] = React.useState("");
  React.useEffect(() => {
    setKeys(/Mac|iP/.test(navigator.platform) ? "⌘K" : "Ctrl K");
  }, []);
  return (
    <button
      type="button"
      onClick={openSearch}
      className="mx-1 flex h-12 shrink-0 items-center gap-3 rounded-full bg-surface-container-high px-4 text-on-surface-variant hover:bg-surface-container-highest"
    >
      <SearchIcon className="text-2xl" />
      <Typography as="span" variant="body-large" className="flex-1 text-start">
        Search
      </Typography>
      {keys && (
        <Typography as="kbd" variant="label-medium" className="font-plain">
          {keys}
        </Typography>
      )}
    </button>
  );
}

// Icon-only trigger for the sub-xl header (sidebar hidden below md).
export function SearchIconButton() {
  return (
    <IconButton aria-label="Search the docs" onClick={openSearch}>
      <SearchIcon />
    </IconButton>
  );
}
