// Generates src/generated/tokens.css and tokens.ts from tokens/tokens.json.
// CSS custom properties follow MD3 naming: --md-sys-color-primary, etc.
// Imported by vite.config.ts (runs on build + watch); also runnable as a CLI.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

export const tokensJsonPath = join(root, "tokens/tokens.json");
export const tokensCssPath = join(root, "src/generated/tokens.css");

/** @typedef {Record<string, string>} TokenGroup */

const camel = (/** @type {string} */ name) =>
  name.replace(/-([a-z0-9])/g, (/** @type {string} */ _, /** @type {string} */ c) =>
    c.toUpperCase(),
  );

export function buildTokens() {
  /** @type {{color: Record<'light'|'dark', TokenGroup>, typescale: Record<string, TokenGroup>} & Record<string, TokenGroup>} */
  const tokens = JSON.parse(readFileSync(tokensJsonPath, "utf8"));
  const outDir = join(root, "src/generated");
  mkdirSync(outDir, { recursive: true });

  const colorVars = (/** @type {'light'|'dark'} */ scheme) =>
    Object.entries(tokens.color[scheme])
      .map(([name, value]) => `  --md-sys-color-${name}: ${value};`)
      .join("\n");

  const flatVars = (/** @type {string} */ group, /** @type {string} */ prefix) =>
    Object.entries(tokens[group])
      .map(([name, value]) => `  --${prefix}-${name}: ${value};`)
      .join("\n");

  const typescaleVars = Object.entries(tokens.typescale)
    .flatMap(([role, props]) =>
      Object.entries(props).map(
        ([prop, value]) => `  --md-sys-typescale-${role}-${prop}: ${value};`,
      ),
    )
    .join("\n");

  const base = [
    '  --md-ref-typeface-brand: "Roboto", system-ui, sans-serif;',
    '  --md-ref-typeface-plain: "Roboto", system-ui, sans-serif;',
    typescaleVars,
    flatVars("shape", "md-sys-shape"),
    flatVars("state", "md-sys-state"),
    flatVars("elevation", "md-sys-elevation"),
    flatVars("motion", "md-sys-motion"),
  ].join("\n");

  const css = `/* Generated by scripts/build-tokens.mjs — do not edit. */
@layer md3.tokens {
  :root {
${colorVars("light")}
${base}
  }

  @media (prefers-color-scheme: dark) {
    :root:not([data-theme='light']) {
${colorVars("dark")}
    }
  }

  [data-theme='dark'] {
${colorVars("dark")}
  }
}
`;

  writeFileSync(tokensCssPath, css);

  // Typed map of CSS variable names, so TS code never hand-writes var() strings.
  const tsEntries = (/** @type {TokenGroup} */ obj, /** @type {string} */ prefix) =>
    Object.keys(obj)
      .map((name) => `  ${camel(name)}: 'var(${prefix}-${name})',`)
      .join("\n");

  const ts = `/* Generated by scripts/build-tokens.mjs — do not edit. */
export const color = {
${tsEntries(tokens.color.light, "--md-sys-color")}
} as const;

export const shape = {
${tsEntries(tokens.shape, "--md-sys-shape")}
} as const;

export const state = {
${tsEntries(tokens.state, "--md-sys-state")}
} as const;

export const elevation = {
${tsEntries(tokens.elevation, "--md-sys-elevation")}
} as const;

export const motion = {
${tsEntries(tokens.motion, "--md-sys-motion")}
} as const;

export type ColorToken = keyof typeof color;
`;

  writeFileSync(join(outDir, "tokens.ts"), ts);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  buildTokens();
  console.log("tokens.css + tokens.ts generated");
}
