// Generates src/generated/tokens.css and tokens.ts from tokens/tokens.json.
// CSS custom properties follow MD3 naming: --md-sys-color-primary, etc.
// Imported by vite.config.ts (runs on build + watch); also runnable as a CLI.
import { mkdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { writeIfChanged } from "./write-if-changed.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

export const tokensJsonPath = join(root, "tokens/tokens.json");
export const tokensCssPath = join(root, "src/generated/tokens.css");
export const tailwindTokensCssPath = join(root, "src/generated/tailwind-tokens.css");

/** @typedef {Record<string, string>} TokenGroup */

const camel = (/** @type {string} */ name) =>
  name.replace(/-([a-z0-9])/g, (/** @type {string} */ _, /** @type {string} */ c) =>
    c.toUpperCase(),
  );

const twLine = (/** @type {string} */ tw, /** @type {string} */ md3) => `  --${tw}: var(--${md3});`;

export function buildTokens() {
  /** @type {{color: Record<'light'|'dark', TokenGroup>, typescale: Record<string, TokenGroup>} & Record<string, TokenGroup>} */
  const tokens = JSON.parse(readFileSync(tokensJsonPath, "utf8"));
  const outDir = join(root, "src/generated");
  mkdirSync(outDir, { recursive: true });

  // Reference tonal palette (theme-independent): the raw hex values sys colors resolve to.
  const refPaletteVars = Object.entries(tokens.ref.palette)
    .map(([tone, value]) => `  --md-ref-palette-${tone}: ${value};`)
    .join("\n");

  // Sys colors point at ref palette tones (values in tokens.json are tone names, not hex).
  const colorVars = (/** @type {'light'|'dark'} */ scheme) =>
    Object.entries(tokens.color[scheme])
      .map(([name, tone]) => `  --md-sys-color-${name}: var(--md-ref-palette-${tone});`)
      .join("\n");

  const flatVars = (/** @type {string} */ group, /** @type {string} */ prefix) =>
    Object.entries(tokens[group])
      .map(([name, value]) => `  --${prefix}-${name}: ${value};`)
      .join("\n");

  const typescaleVars = Object.entries(tokens.typescale)
    .flatMap(([role, props]) =>
      Object.entries(props).map(
        ([prop, value]) => `  --md-sys-typescale-${role}-${prop}: ${value};`,
      ),
    )
    .join("\n");

  const base = [
    '  --md-ref-typeface-brand: "Roboto", system-ui, sans-serif;',
    '  --md-ref-typeface-plain: "Roboto", system-ui, sans-serif;',
    typescaleVars,
    flatVars("shape", "md-sys-shape"),
    flatVars("state", "md-sys-state"),
    flatVars("elevation", "md-sys-elevation"),
    flatVars("motion", "md-sys-motion"),
    flatVars("z-index", "md-ref-z-index"),
  ].join("\n");

  const css = `/* Generated by scripts/build-tokens.mjs — do not edit. */
@layer theme {
  :root {
    color-scheme: light;
${refPaletteVars}
${colorVars("light")}
${base}
  }

  @media (prefers-color-scheme: dark) {
    :root:not([data-theme='light']) {
      color-scheme: dark;
${colorVars("dark")}
    }
  }

  /* Element-scoped (not :root) so a subtree can pin its own scheme inside the other. */
  [data-theme='light'] {
    color-scheme: light;
${colorVars("light")}
  }

  [data-theme='dark'] {
    color-scheme: dark;
${colorVars("dark")}
  }
}
`;

  writeIfChanged(tokensCssPath, css);

  // Tailwind v4 theme: MD3 tokens as utility names (bg-primary, text-title-large,
  // rounded-extra-large, shadow-level1, ease-emphasized, font-brand). `inline`
  // keeps var() references so values track the active md3 theme at runtime.
  const twColors = Object.keys(tokens.color.light).map((name) =>
    twLine(`color-${name}`, `md-sys-color-${name}`),
  );
  const twText = Object.keys(tokens.typescale).flatMap((role) => [
    twLine(`text-${role}`, `md-sys-typescale-${role}-size`),
    twLine(`text-${role}--line-height`, `md-sys-typescale-${role}-line-height`),
    twLine(`text-${role}--font-weight`, `md-sys-typescale-${role}-weight`),
    twLine(`text-${role}--letter-spacing`, `md-sys-typescale-${role}-tracking`),
  ]);
  // corner-none/full match Tailwind's built-in rounded-none/full — skip them.
  const twRadius = Object.keys(tokens.shape)
    .filter((name) => !/-(none|full)$/.test(name))
    .map((name) => twLine(`radius-${name.replace(/^corner-/, "")}`, `md-sys-shape-${name}`));
  const twShadows = Object.keys(tokens.elevation).map((name) =>
    twLine(`shadow-${name}`, `md-sys-elevation-${name}`),
  );
  const twEasings = Object.keys(tokens.motion)
    .filter((name) => name.startsWith("easing-"))
    .map((name) => twLine(`ease-${name.replace(/^easing-/, "")}`, `md-sys-motion-${name}`));
  // z-index ref tokens are not exposed as Tailwind utilities — v4 has no z-index theme
  // namespace, so they'd be inert. Consume them directly via var(--md-ref-z-index-*).

  const twCss = `/* Generated by scripts/build-tokens.mjs — do not edit. */
/* Tailwind v4 theme exposing the MD3 system tokens as utilities. Import inside
   your Tailwind entry CSS (after \`@import "tailwindcss"\`); the md3 stylesheet
   (styles.css or tokens.css) must also be loaded for the vars to resolve. */
@theme inline {
${[
  "  /* color tokens */",
  ...twColors,
  "  /* fonts */",
  twLine("font-brand", "md-ref-typeface-brand"),
  twLine("font-plain", "md-ref-typeface-plain"),
  "  /* typography */",
  ...twText,
  "  /* shape */",
  ...twRadius,
  "  /* elevation */",
  ...twShadows,
  "  /* motion */",
  ...twEasings,
].join("\n")}
}
`;
  writeIfChanged(tailwindTokensCssPath, twCss);

  // Typed map of CSS variable names, so TS code never hand-writes var() strings.
  const tsEntries = (/** @type {TokenGroup} */ obj, /** @type {string} */ prefix) =>
    Object.keys(obj)
      .map((name) => `  ${camel(name)}: 'var(${prefix}-${name})',`)
      .join("\n");

  const ts = `/* Generated by scripts/build-tokens.mjs — do not edit. */
export const color = {
${tsEntries(tokens.color.light, "--md-sys-color")}
} as const;

export const shape = {
${tsEntries(tokens.shape, "--md-sys-shape")}
} as const;

export const state = {
${tsEntries(tokens.state, "--md-sys-state")}
} as const;

export const elevation = {
${tsEntries(tokens.elevation, "--md-sys-elevation")}
} as const;

export const motion = {
${tsEntries(tokens.motion, "--md-sys-motion")}
} as const;

export const zIndex = {
${tsEntries(tokens["z-index"], "--md-ref-z-index")}
} as const;

export type ColorToken = keyof typeof color;
`;

  writeIfChanged(join(outDir, "tokens.ts"), ts);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  buildTokens();
  console.log("tokens.css + tokens.ts generated");
}
