/// <reference types="vite/client" />
declare module "*.css";

// Demo registry generated by the md3:demos plugin (see vite.config.ts).
declare module "virtual:md3-demos" {
  export const DEMOS: Record<
    string,
    {
      title: string;
      load: () => Promise<{ default: React.ComponentType }>;
      // Shiki-highlighted demo sources (md3:demo-code virtual module).
      code: () => Promise<{ FILES: { name: string; code: string; html: string }[] }>;
    }
  >;
}
